name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        if: github.ref == github.ref == 'refs/heads/staging'
        run: node scripts/bump-version.js patch

      - name: Commit changes
        if: github.ref == github.ref == 'refs/heads/staging'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package.json src/version.js
          git commit -m "Bump version number"

      - name: Push changes
        if: github.ref == github.ref == 'refs/heads/staging'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set database URL based on branch
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
            echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL_PRODUCTION }}" >> $GITHUB_ENV
          else
            echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Apply Supabase migrations
        run: supabase db push --db-url $SUPABASE_DB_URL
